### ISSUE TITLE
hope multivariate version

### ISSUE THREAD

**Issue by presburger** [angus924/hydra#1]
GOOD JOB, Thank U.

**Comment by angus924** [comment]
Thanks @Presburger.

I've uploaded a makeshift multivariate version of Hydra in `hydra_multivariate.py`.  (Note that this is still experimental, I've only checked that it runs, I don't really know how well it works.  It's probably also not particularly efficient at this stage.  I will keep the univariate and multivariate code separate for the time being.)

The multivariate version works (at least, for the moment) by assigning a random subset of channels to each of the *g* groups (using groupwise/depthwise convolution with `groups = g`).  You have to pass `num_channels` (i.e., the number of channels in the multivariate input) as an additional argument to the constructor.  Otherwise its usage is the same as for the univariate version.

```python
from hydra_multivariate import HydraMultivariate

[...] # load data

transform = HydraMultivariate(X_training.shape[-1], num_channels = X_training.shape[1])

[...]
```

A slight variation on this idea is to use multivariate/multichannel kernels.  You just need to change `torch.randn(divisor, k * _g, 1, 9)` to `torch.randn(divisor, k * _g, num_channels_per, 9)` in `__init__(...)`, and then change `.sum(2)` to `.reshape(num_examples, -1, length)` in `forward(...)`.

**Comment by presburger** [comment]
Thank You, @angus924 I will try to use this. minirocket is a excellent features extract tools. Thanks.
