### ISSUE TITLE
is it possible to implement hydra with numpy?

### ISSUE THREAD

**Issue by presburger** [angus924/hydra#2]
pytorch is too heavy for me.

**Comment by angus924** [comment]
Hi @Presburger.

It is *possible*...  It should be relatively straightforward to reimplement Hydra in NumPy / Numba.  I have considered it, but I only have the PyTorch implementation for the moment.  (PyTorch is very well suited to the way Hydra works, and what operations need to be performed.)

Is there a particular issue that you have with using / installing PyTorch (e.g., is the package too big)?  You only need the cpu version in order to use Hydra, and as far as I know that is quite a bit smaller than, e.g., the "full" CUDA package.
